language: generics
sudo: required
services:
  - docker

before_install:
  - docker build -t kanti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kanti/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region:
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-451958814529"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY